package com.bs.pojo;
// Generated Oct 18, 2016 6:42:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private int departmentId;
     private Location location;
     private Manager manager;
     private String departmentName;
     private Set jobhistories = new HashSet(0);
     private Set employees = new HashSet(0);

    public Department() {
    }

	
    public Department(int departmentId) {
        this.departmentId = departmentId;
    }
    public Department(int departmentId, Location location, Manager manager, String departmentName, Set jobhistories, Set employees) {
       this.departmentId = departmentId;
       this.location = location;
       this.manager = manager;
       this.departmentName = departmentName;
       this.jobhistories = jobhistories;
       this.employees = employees;
    }
   
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Manager getManager() {
        return this.manager;
    }
    
    public void setManager(Manager manager) {
        this.manager = manager;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Set getJobhistories() {
        return this.jobhistories;
    }
    
    public void setJobhistories(Set jobhistories) {
        this.jobhistories = jobhistories;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


