package com.bs.pojo;
// Generated Oct 18, 2016 6:42:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Jobhistory generated by hbm2java
 */
public class Jobhistory  implements java.io.Serializable {


     private int empId;
     private Department department;
     private Employee employee;
     private Jobs jobs;
     private Date startDate;
     private Date endDate;

    public Jobhistory() {
    }

	
    public Jobhistory(Employee employee) {
        this.employee = employee;
    }
    public Jobhistory(Department department, Employee employee, Jobs jobs, Date startDate, Date endDate) {
       this.department = department;
       this.employee = employee;
       this.jobs = jobs;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


