package com.bs.pojo;
// Generated Oct 18, 2016 6:42:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
public class Regions  implements java.io.Serializable {


     private Integer regionsId;
     private String regionsName;
     private Set locations = new HashSet(0);

    public Regions() {
    }

    public Regions(String regionsName, Set locations) {
       this.regionsName = regionsName;
       this.locations = locations;
    }
   
    public Integer getRegionsId() {
        return this.regionsId;
    }
    
    public void setRegionsId(Integer regionsId) {
        this.regionsId = regionsId;
    }
    public String getRegionsName() {
        return this.regionsName;
    }
    
    public void setRegionsName(String regionsName) {
        this.regionsName = regionsName;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


